## NumPy Arrays

In [1]:
import numpy as np

In [6]:
my_list = [1,2,3]

In [7]:
my_list

[1, 2, 3]

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [10]:
arr[2]

3

In [11]:
my_mat = [[1,2,3],[4,5,6],[6,7,8]]

In [12]:
matrix = np.array(my_mat)

In [13]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

### Range

In [14]:
np.arange(0,10,3)
# Range from 0-10
# Jump Size 3

array([0, 3, 6, 9])

In [15]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [16]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
np.random.rand(5)

array([ 0.32123745,  0.38607077,  0.19606483,  0.1951057 ,  0.24449241])

In [19]:
np.random.randn(5)

array([-1.15764435,  0.71575569,  0.42982324,  0.33066473,  0.46853442])

In [20]:
np.random.randint(1,250,7)

array([162,  73, 191, 148, 246,  71, 106])

In [21]:
arr = np.arange(25)

In [22]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)

In [24]:
ranarr

array([14, 42, 20,  3, 11, 43, 47, 39, 25, 49])

### Reshape 

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr.shape

(25,)

In [27]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [28]:
ranarr.min()

3

In [29]:
ranarr.argmin()

3

In [30]:
ranarr.max()

49

In [31]:
ranarr.argmax()

9

#### Data Types

In [32]:
ranarr.dtype

dtype('int32')

In [33]:
arr.dtype

dtype('int32')

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [99]:
arr=np.arange(10).reshape(5,5)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
rowArr = arr
#Setting a value with index range (Broadcasting)
rowArr[2:5,:]=100
# Same as rowArr[2:5]=100 
#Show
rowArr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [62]:
colArr = np.arange(25).reshape(5,5)
#Setting a value with index range (Broadcasting)
colArr[:,2:5]=100
#Show
colArr

array([[  0,   1, 100, 100, 100],
       [  5,   6, 100, 100, 100],
       [ 10,  11, 100, 100, 100],
       [ 15,  16, 100, 100, 100],
       [ 20,  21, 100, 100, 100]])

In [73]:
# Take Slice of 
sliceArr=arr[1:4,2:4]
sliceArr

array([[  7,   8],
       [100, 100],
       [100, 100]])

In [74]:
sliceArr[0,0]=1200

In [75]:
arr

array([[   0,    1,    2,    3,    4],
       [   5,    6, 1200,    8,    9],
       [ 100,  100,  100,  100,  100],
       [ 100,  100,  100,  100,  100],
       [ 100,  100,  100,  100,  100]])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [2]:
arr_2d = np.array([[5,12,11],[22,9,2],[6,12,22]])

In [17]:
# Get 2nd Row
arr_2d[1]

array([22,  9,  2])

In [20]:
# Get 2x3 element
arr_2d[1][2]

2

In [21]:
arr_2d[1,2]

2

In [24]:
# Fetch 2nd Column
arr_2d[:,1]

array([12,  9, 12])

In [27]:
# Fetch slice of  array

arr_2d[:2,1:]

array([[12, 11],
       [ 9,  2]])

In [38]:
arr_2d[0:2,0:2]

array([[ 5, 12],
       [22,  9]])

### Conditional Selection

In [41]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [44]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr_2dx = np.arange(50).reshape(5,10)

In [47]:
arr_2dx

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr_2dx[:3,4:6]

array([[ 4,  5],
       [14, 15],
       [24, 25]])

In [ ]:
arr_2dx

# Numpy Operation

* Array with Array
* Array with Scalar
* Universal Array Function

In [53]:
array_opn = np.arange(10)
array_opn

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

####  Array with Array 

In [68]:
array_opn + array_opn

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
array_opn * array_opn

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [71]:
# Warning due to divide by zero error
array_opn / array_opn

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

#### Array with Scalar 

In [72]:
1/array_opn

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [73]:
-1/array_opn

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([       -inf, -1.        , -0.5       , -0.33333333, -0.25      ,
       -0.2       , -0.16666667, -0.14285714, -0.125     , -0.11111111])

In [74]:
array_opn **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

#### Universal Array Functions

In [75]:
np.exp(array_opn)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [76]:
np.max(array_opn)

9

In [77]:
array_opn.max()

9

In [78]:
np.sin(array_opn)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])